### ISSUE TITLE
Instructions for using gaps with an existing project

### ISSUE THREAD

**Issue by Arthaey** [danthareja/node-google-apps-script#1]

**Comment by danthareja** [comment]
Hey @Arthaey, could your clarify your question a bit? Do you mean an exiting project that you have already downloaded locally, and how to use gaps to manage it's upload?

**Comment by Arthaey** [comment]
I already have a Google Apps Script project that I created via clicking on "Tools > Script Editor" from a Google Document. I'd like to put the script files of that existing project into Github.

So I haven't used gaps yet, I'd like to, but the current instructions only talk about creating a brand new project.

**Comment by danthareja** [comment]
gaps is actually designed to work with existing Google Apps Script projects. The one caveat is that your project must be a "standalone" project, and not "bound" to a specific sheet (currently the Drive API does not support the download of bound projects). You'll know if your project is bound if you can only access it via "Tools > Script Editor". If you see your script in your main Drive folder, it's a standalone and gaps will totally work with it. Does this help?

A standalone project:
![screen shot 2015-04-01 at 8 02 47 pm](https://cloud.githubusercontent.com/assets/6980359/6956946/3341c142-d8aa-11e4-8768-b76816bbe411.png)

[You can learn more about script binding here](https://developers.google.com/apps-script/guides/bound) and [review the limitations of the Import/Export API here](https://developers.google.com/apps-script/import-export)

**Comment by danthareja** [comment]
Also, thanks for reminding me about this limitation @Arthaey. I'll be sure to update the documentation to more clearly reflect this.

**Comment by danthareja** [comment]
For the sake of maintenance, I'm closing this issue for now. Please reopen another one if you do have any further questions.

Thanks for your contribution!
