### ISSUE TITLE
Error running init command { [Error: EISDIR... }

### ISSUE THREAD

**Issue by dsernst** [danthareja/node-google-apps-script#10]
After creating the API keys, downloading the JSON, running `gaps init`, and visiting the one-time authorization page, I pasted in the `?code=` parameter, as the README instructs. But I was given the following error:

`Error running init command { [Error: EISDIR, open '/Users/dsernst/.gaps'] errno: 28, code: 'EISDIR', path: '/Users/dsernst/.gaps' }`

It turns out we were thinking along similar lines: these config files belong in a place like `.gaps` in the Home Directory. The problem was I had assumed this `.json` file was going to be needed for the long-term, so I had already manually created my own `~/.gaps` folder and stuck it in there.

I was able to get past this error by moving the `.json` file out of that folder, deleting the folder, and then re-running `gaps init`. There might be an opportunity there for more clear error handing, if this issue continues to come up for other users. :smile:

**Comment by danthareja** [comment]
I totally agree, the file storage is quite obfuscated right now. Thanks for your thorough description of the problem!

**Comment by danthareja** [comment]
Addressed in v1.0. Thanks!
