### ISSUE TITLE
Error code 400 when pushing

### ISSUE THREAD

**Issue by fsrc** [danthareja/node-google-apps-script#11]
I'have successfully cloned, added files and pushed them. Now when I try to update existing files i get this:

```
Pushing /home/fredrik/src/CRM-Data back up to Google Drive...
Error running upload command { [Error: Bad Request]
  code: 400,
  errors: 
   [ { domain: 'global',
       reason: 'badRequest',
       message: 'Bad Request' } ] }
```

Just ask if you need more information.

Fredrik

**Comment by shrugs** [comment]
Could be an issue with state being out of sync. To fix, download the remote project to a separate directory, overwrite your local manifest with the one, and then upload again.

Alternatively it could be a syntax error in the server-side code.

**Comment by danthareja** [comment]
I'm triaging old issues with the new release of 1.0.0. I'm closing this for now (there are some possible reasons for the 400 error in the README), if it comes up again please open a new issue

**Comment by Moradnejad** [comment]
it's because of "Content Security Policy" of the response.
