### ISSUE TITLE
Trouble authenticating with client_secret.json

### ISSUE THREAD

**Issue by thinkle** [danthareja/node-google-apps-script#18]
I'm having trouble successfully authenticating.

My first problem I think is that I'd set the project type to web application and therefore my JSON file had no redirect URL:

Here's the error output there:
$ gaps init /home/tom/client_secret.json 

/usr/local/lib/node_modules/node-google-apps-script/lib/commands/init.js:34
    auth.redirect_uri = credentials.web.redirect_uris[0];
                                                     ^
TypeError: Cannot read property '0' of undefined
    at /usr/local/lib/node_modules/node-google-apps-script/lib/commands/init.js:34:54
    at fs.js:268:14
    at Object.oncomplete (fs.js:107:15)

A little detective work shows that my JSON file in fact had no redirect_utis, so that makes sense.

I then discovered if I downloaded a key for an "Other" application I got a key with a localhost redirect value, which seems like the right thing. However, this time I get a less helpful error from gaps:

$ gaps init /home/tom/Downloads/otherother.json 
Error running init command Path did not include correct credentials. Please check that you downloaded the right JSON credentials.

Any help would be appreciated. I'd also suggest adding clarity in the docs about what kind of project to create in the google developer console.

**Comment by thinkle** [comment]
Just confirmed the credentials are valid -- was able to use same credentials to log in with gdcmdtools...

**Comment by lucasconstantino** [comment]
Hello,

Just had the same problem. Solved it by fulfiling the "Authorized redirect URIs", on the OAuth Client ID configuration page, with the value *http://localhost/callback".

This redirect is only a callback page to which OAuth will send the user upon authorization for the App. It's basically where the user goes to after authorization, and is send with a query string suffix containg the authorization code, which the requesting application should use to do further requests. In case of _node-google-apps-script_, you will only need to grab this code from the query string to use while initializing with th CLI, so the url must match nothing: indeed it's more guaranteed to work if you give a non existing url as callback.

If you have any further question, please let me know, so I can try and explain myself better.

**Comment by danthareja** [comment]
I'm triaging old issues with the release of 1.0.0. The auth process has been completely overhauled. If this is still a problem, please open a new issue.

**Comment by orenyny** [comment]
@lucasconstantino Thanks for the tip. It helped me understand that I did not create the credentials correctly (the instructions are not so clear), but thanks to you I corrected it. Thanks!
