### ISSUE TITLE
can't change type of existing file

### ISSUE THREAD

**Issue by xguntis** [danthareja/node-google-apps-script#2]
Thank you! Thank you! Thank you!

I needed this so badly to be able to do GIT version control for my GAS project. Previous version did not work for uploading. This time it works as expected!

Just one thing - for every file that is uploaded it says `can't change type of existing file`. Should it be ignored?

```
xguntis@EliteBook:~/Downloads/temp/gapstest$ gas upload
can't change type of existing file
...
can't change type of existing file
Success uploading for gss
```

**Comment by danthareja** [comment]
Oh how interesting @xguntis. Can you confirm that your local changes are being accurately reflected in Google after uploading them? If you're getting these errors I would expect the upload not going through correctly.

**Comment by xguntis** [comment]
Yes, I can confirm that changes are reflected accurately. Tested on one of the *.js files which i changed on my local drive, uploaded and the resulting *.gs file was also changed.

**Comment by danthareja** [comment]
I'm not sure about this one right now. I'll keep this issue open while I look into it

**Comment by xguntis** [comment]
you may close this now. It was generating errors when i was using gas, not gaps. Now following your instructions and everything works just wonderfull :)

**Comment by danthareja** [comment]
Glad to hear!
