### ISSUE TITLE
Unexpected identifier error

### ISSUE THREAD

**Issue by carlsaturnino** [danthareja/node-google-apps-script#20]
I got a syntax error when trying to run `gapps atuh <client.*.json>`

```
/usr/lib/node_modules/node-google-apps-script/lib/commands/auth.js:82
      scope: GOOGLE_AUTH_SCOPE,
      ^^^^^
```

Also, got the same error in https://tonicdev.com/npm/node-google-apps-script.

**Comment by danthareja** [comment]
Oof, that's embarassing. I'll fix this in a hot second. Maybe it's time for those unit tests I keep thinking about...
