### ISSUE TITLE
Auto-completion

### ISSUE THREAD

**Issue by medric** [danthareja/node-google-apps-script#26]
Hello,

I just wanted to know if there were a way to get an auto-completion system (for API methods etc.), as the one you can get on the online editor, when you develop on your local IDE or text editor.

Thank you.

**Comment by hess-g** [comment]
There is currently no public API that exposes that metadata. However, the Apps Script team has that feature on our backlog.

**Comment by danthareja** [comment]
Yeah unfortunately this is a limitation of the Google Drive API right now. If it ever gets implemented, I'll happily add it to gapps.

**Comment by medric** [comment]
Ok, thank you for your answers. Another idea would be to implement a provider for Atom using the autocomplete-plus API. So this would be restricted to Atom, and would have to be done from scratch. I think i'll have a look at it.

**Comment by danthareja** [comment]
That would be great @medric! I'm excited to see what you come up with :smile:
