### ISSUE TITLE
git and .manifest.json

### ISSUE THREAD

**Issue by simbalsyd** [danthareja/node-google-apps-script#3]
Hi

Your project is great and exactly what I have been looking for!

I have been trying to download a project and put it into git. Everything works fine but I have a problem with the file .manifest.json. It looks like git is adding \r .

Is the file .manifest.json supposed to be in the git or can it be ignored (in .gitinore). 

Maybe you have a recommended way how to handle .manifest.json?

Thanks
Anders Sneckenborg

**Comment by danthareja** [comment]
Hey Anders! .manifest.json is only needed locally for gaps to work correctly. The easiest way to handle it is as you suggested to add it to .gitignore. Thanks for your issue, I'll make sure to update the document to make this best practice more clear.

**Comment by danthareja** [comment]
I'm going to close this issue for now. If you feel like there's still some question left unanswered, please don't hesitate to open a new one! Thanks for the feedback @simbalsyd
