### ISSUE TITLE
Project Needs Automated Test Framework

### ISSUE THREAD

**Issue by 0cjs** [danthareja/node-google-apps-script#30]
The project should have an automated test framework that gives at least basic coverage, if if it can't be perfect. This will both help reduce tedious manual testing and make it easier for new developers to contribute.

As a side note, introducing automated testing in projects not originally designed for it typically introduces major structural changes to accommodate the extra functionality needed to support automated testing.

**Comment by 0cjs** [comment]
There's both a unit test and functional test framework in PR #28. It's mixed in with other changes, though; if you don't want them all you'll have to pick out the bits you want.

**Comment by lricoy** [comment]
Working on that :)
