### ISSUE TITLE
push fails

### ISSUE THREAD

**Issue by bline** [danthareja/node-google-apps-script#36]
We are working with Google Apps Script for non-profit business. I believe it's different that the regular google apps.

With the current gapps code, I can pull projects but push always shows Upload Failed because of File Not Found.

Have you heard of this issue? Looking for a work-a-around if possible.

Thanks!

**Comment by hess-g** [comment]
It sounds like you are using container-bound scripts - Scripts that were created by opening the Script Editor from a Sheets or Docs file. The Google Drive API currently only supports standalone scripts - Scripts created from and opened in the Apps Script Google Drive app.

If there is no affinity to the actual sheet or doc, you can copy your code to a new standalone script, and then gapps will work for the upload case.

**Comment by bline** [comment]
Thank you, that is indeed the case. However, I now get 
An error occured while running upload command: Bad Request
Upload failed.

**Comment by bline** [comment]
So it did seem to upload some files. Of 13 files, 4 files were sent. Running it over and over doesn't add more files.

I ran into this type of thing trying to sync a list page from a spreadsheet to google sites. Same error too. I think they may throttle non-profits requests and just give an error, seems pretty lame to me.

I'll dig deeper and see if there is a way to do an incremental sync.

**Comment by hess-g** [comment]
There are a few other things that could cause the bad request response. It typically is either badly formatted code (e.g. code that would trigger a failure when trying to save in the Script Editor), or a totally empty file (you can save those in the Script Editor, but not via the API). I recommend running your code through jslint or the like prior to upload, to see if there are any egregious coding errors.

**Comment by oshliaer** [comment]
@bline 
A tip. You could upload a part of the files. Be careful if you're updating existing files.

**Comment by lricoy** [comment]
Closing since it looks idle. Please reopen if still an issue.
