### ISSUE TITLE
gapps auth doesn't allow multiple projects

### ISSUE THREAD

**Issue by stmcallister** [danthareja/node-google-apps-script#37]
I noticed that when I tried to auth a second AppsScript project I was given the message that the ~/.gapps file already existed, and that I needed to remove it so that I could authenticate the connection with the current project.

Is there a reason why we couldn't move the .gapps file to the project root rather than the machine's user directory? That way we could authenticate multiple gapps projects.

**Comment by oshliaer** [comment]
- You don't need to oauth twice. Or
- If you have to separate your oauth for multiple users (not projects) you could look at #29 and [An idea for the overwrite .gapps file path](https://gist.github.com/oshliaer/16886a0398b284dd776f)

**Comment by stmcallister** [comment]
Ah, thank you for that clarification. I thought it was by project, but you're right. It's by account. I'll checkout  the idea for overwriting .gapps file path. Thanks!
