### ISSUE TITLE
Rejecting file ID on `gapps init` when ID begins with M

### ISSUE THREAD

**Issue by rafaelalemar** [danthareja/node-google-apps-script#38]
You guys have committed a version that block gapps innit when ID begins with M, but all my bounded scripts starts with M. I know I can't push code to bounded scripts, but I could pull it. I used to backup my bounded scripts this way. Any work around?

**Comment by hess-g** [comment]
Rafael - The "m" ID is the project key. You need to use the Drive File ID
for the script, which begins with a "1", and can be obtained from the URL
when you open the script editor from your bound script.

**Comment by oshliaer** [comment]
The `eval` could help for this.
- Copy the [example](https://docs.google.com/spreadsheets/d/1nleri9TedljONIHuKCj3RbrWBGw5SVvb1YW9nDuR-Wc/copy)
- Get the [source](https://script.google.com/macros/s/AKfycbzXMlbXwYFfAE5t_YEGXKAxuN-uLck9hmXQLlVgB_cIblaDtWaJ/exec)

## Code.gs

```
function onOpen(){
  magic(getSource(), 'onOpen');
}

function getSpreadsheetId(){
  magic(getSource(), 'getSpreadsheetId');
}

function magic(source, fn){
  eval('(' + source + ')')(fn);
}

function getSource(){
  return HtmlService.createHtmlOutputFromFile('source').getContent();
}

function doGet(){
  return ContentService.createTextOutput(getSource());
}
```

## source.html

```
function(fn){

  var ___ = {};  
  ___.args = Array.prototype.slice.call(arguments, 1);

  ___.onOpen = function(){
    SpreadsheetApp.getUi().createMenu('menu').addItem('get id', 'getSpreadsheetId').addToUi();
  };

  ___.getSpreadsheetId = function(){
    SpreadsheetApp.getUi().alert(SpreadsheetApp.getActive().getId());
  };

  return ___[fn].apply(undefined, ___.args);
}
```

**Comment by rafaelalemar** [comment]
@hess-g Thanks for the quick reply. My old bound script file ID all start with M. I just created a new spreadsheet and open the script editor to confirm the file ID starts with 1. But my old ones still start with M and the project key starts with 1. So, I pick up the project key and it worked...

@oshliaer Your script would give me the spreadsheet id, not the script ID.
