### ISSUE TITLE
Initializing git repo causes gaps upload error

### ISSUE THREAD

**Issue by gisellegk** [danthareja/node-google-apps-script#5]
Hi there,

I successfully ran `gaps download` and `gaps upload` on an existing project, then tried to `gaps upload` after initializing my local git repo. It's now throwing an "Unsupported file type found" error. I think it's because of the .git file, which is the only file that isn't .js or .html.

Am I missing something? I will try putting the directory in a parent and initialize that as a repo..

**Comment by danthareja** [comment]
Ah, great find! Right now i've hardcoded which files to ignore as only .manifest.json right now. You have me thinking that it makes more sense to only include .js and .html files to export instead of trying to think of all the possible files to ignore. I'll work on a patch for this!

**Comment by danthareja** [comment]
That should do it. I just republished it to npm as well, you'll have to give it a reinstall. Please let me know how it works for you.

**Comment by gisellegk** [comment]
I uninstalled and reinstalled, and I'm still getting the same error:

```
giselle@bluebird:~/SignIn-AppsScript$ gaps upload
Pushing back up to Google Drive...
Great success!
giselle@bluebird:~/SignIn-AppsScript$ git init
Initialized empty Git repository in /home/giselle/SignIn-AppsScript/.git/
giselle@bluebird:~/SignIn-AppsScript$ gaps upload
Pushing back up to Google Drive...
/usr/lib/node_modules/node-google-apps-script/lib/utils/manifestor.js:67
  throw new Error('Unsupported file type found. Google Apps Script only allows
        ^
Error: Unsupported file type found. Google Apps Script only allows .js and .html
    at getFileType (/usr/lib/node_modules/node-google-apps-script/lib/utils/manifestor.js:67:9)
    at getFileInManifest (/usr/lib/node_modules/node-google-apps-script/lib/utils/manifestor.js:58:47)
    at /usr/lib/node_modules/node-google-apps-script/lib/utils/manifestor.js:22:26
    at /usr/lib/node_modules/node-google-apps-script/node_modules/node-dir/lib/readfiles.js:99:34
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

I tried uninstalling and reinstalling again and I'm pretty sure this is the correct version.
`unbuild node-google-apps-script@0.1.2`

**Comment by danthareja** [comment]
Shoot! I'll have to give this a more thorough look. I'll get back to this, sorry about the inconvenience

**Comment by gisellegk** [comment]
Can you make sure the right version is published to npm? The manifestor file on my computer doesn't have your fix on it despite reinstall.

edit:  it works with local changes :)

**Comment by danthareja** [comment]
Glad to hear it works with local changes! I just republished to npm, and when I downloaded it to test, manifestor was up to date.

Can you confirm things working on your end?

**Comment by gisellegk** [comment]
Yep, it's working for me too! Glad we got that sorted out. Thanks so much!

**Comment by danthareja** [comment]
My pleasure. Thank you for your contribution!
