### ISSUE TITLE
Trouble with gapps auth

### ISSUE THREAD

**Issue by danielezappala** [danthareja/node-google-apps-script#53]
Hi! sorry cause I'm real beginner with node, npm and so on
I tried to auth a project both on Windows and Mac. On windows no problem, on mac instead I have a command not found when I launch gapps auth ~/Downloads/client_secret.json, I tried also with sudo but nothing to do I always obtain -bash: gapps: command not found
Could you help me please ?

**Comment by shrugs** [comment]
Seems like the command isn't in your `PATH` environment variable, so your shell can't find it. How did you install node and `node-google-apps-script`? Are you using a node version manager like `nvm`?

**Comment by lricoy** [comment]
Hi @danielezappala Did it work for you at the end? I agree with @Shrugs looks like the command is not in your `PATH`. I will close this but please reopen if you are still having issues with `gapps`
