### ISSUE TITLE
Internal Error when push

### ISSUE THREAD

**Issue by sunfmin** [danthareja/node-google-apps-script#60]
```
$ gapps push
Pushing back up to Google Drive...
An error occured while running upload command: Internal Error
Upload failed.
```

Is it possible to know what is the internal error?

**Comment by oshliaer** [comment]
Wait for a while and try again.

**Comment by lricoy** [comment]
I got this once and it worked after waiting for a while as well. Closing this but please reopen if it keeps happening @sunfmin
