### ISSUE TITLE
How to run Google Apps Script projects on my local machine?

### ISSUE THREAD

**Issue by julesmoretti** [danthareja/node-google-apps-script#63]
NEED:
The ability to run google scripts that is currently written for google spreadsheets but on my local machine rather than through the web interface.

EXPECTATION:
Using node-google-apps-script I can edit my scripts locally using Sublime text editor, test them locally and then push those online through Google script API integration.

PROBLEM:
The readme information is missing some steps for example.
When in google spreadsheets click on `Tools > script editor`
Once in Script editor click on `Publish > Deploy as API executable...`

These are not currently informations I can even read from your documentation...

Any help would be very helpful.

**Comment by oshliaer** [comment]
I'm not sure that It's possible to do your tasks with [ngas](./../). Try something else like [gas-local](https://github.com/mzagorny/gas-local) or [ggsrun](https://github.com/tanaikech/ggsrun)

**Comment by lricoy** [comment]
Hi @julesmoretti have you tried @oshliaer's suggestions?

**Comment by julesmoretti** [comment]
@lricoy I have not sorry
@oshliaer thank you for the recommendations ggsrun looks promising :)

**Comment by aurelienshz** [comment]
I feel like this falls out of scope of this tool, and [gas-local](https://github.com/mzagorny/gas-local) README explicitely advises to use gapps to push/pull the project to/from Google Drive. I'm closing this issue, since it seems irrelevant to this project.

**Comment by robertocabellon** [comment]
Even though this issue is old and already closed, this info may help future internauts, that reach this forever-valid question!
You may try [Google's clasp](https://github.com/google/clasp). This may be the tool you were looking for..
