### ISSUE TITLE
Cannot push with non-standalone file

### ISSUE THREAD

**Issue by AdrienLemaire** [danthareja/node-google-apps-script#66]
I have a script bound to a spreadsheet file, and I was able to `gapps init id` using the script id from the Project properties. It downloaded my files without any problems.

On the other side, when trying to `gapps push`, it returns the `File not found` error. Is that why you recommended to only use standalone scripts ? I'm a newbie with google scripts, what would then be the good practice to access a spreadsheet's data from a standalone script ?

Thanks in advance for the support

**Comment by oshliaer** [comment]
You can't edit bound scripts. 

The best way for me is create a trigger programmatically https://developers.google.com/apps-script/guides/triggers/installable#managing_triggers_programmatically

```js
function createSpreadsheetEditTrigger() {
  var ss = SpreadsheetApp.getActive();
  ScriptApp.newTrigger('myFunction')
      .forSpreadsheet(ss)
      .onOpen()
      .create();
}
```

**Comment by lricoy** [comment]
Hey @Fandekasp . Did that solution work for you? I will close this but please reopen if needed.
