### ISSUE TITLE
Is it supported by latest node?

### ISSUE THREAD

**Issue by kc1** [danthareja/node-google-apps-script#68]
Hi,

I've just come across this, (Thanks for making it!), but I'm wondering if the current version of node supports it? https://nodejs.org/en/

**Comment by oshliaer** [comment]
@kc1 This is my console now
```sh
> user@bigpc  ~  nodejs --version                          ✔  1489  23:22:54 
v8.6.0
```
The gapps works fine.

**Comment by kc1** [comment]
Thanks
