### ISSUE TITLE
Can I perform  "Publish>Deploy as API executable" programmatically using c#/.Net?

### ISSUE THREAD

**Issue by asadmkhan** [danthareja/node-google-apps-script#70]
I have a google sheet containing script, I want to execute this script programmatically for any user (public). Can I perform  "Publish>Deploy as API executable" programmatically?

@lastobelus @oshliaer @peterherrmann @hess-g @gunar @sbgood

**Comment by oshliaer** [comment]
@asadmkhan , it's impossible.

**Comment by peterherrmann** [comment]
Add a doGet() function to the apps script and deploy as web app. See the
docs https://developers.google.com/apps-script/guides/html/

**Comment by asadmkhan** [comment]
@peterherrmann  i want to deploy as Executable API

**Comment by lricoy** [comment]
I am also not sure that this is possible. Any more thoughts on that @oshliaer ?

**Comment by aurelienshz** [comment]
AFAIK, performing Publish > Deploy as API executable allows you to run the script through Google's [Execution API](https://developers.google.com/apps-script/guides/rest/api).

You might be interested in [Triggers](https://developers.google.com/apps-script/guides/triggers/), that allow you to "run a function automatically when a certain event, like opening a document, occurs" (I'm not sure if that's relevant to your question?).

**Comment by lricoy** [comment]
Closing because since it looks idle.

**Comment by gunar** [comment]
@lricoy yes, we are all very much interested still!

**Comment by lricoy** [comment]
Hey @gunar good to know 😃 
Will leave it close and keep tabs on #32
