### ISSUE TITLE
appsscript.json (just introduced by Google) not supported. I've made a fix

### ISSUE THREAD

**Issue by rakeshjoezoo** [danthareja/node-google-apps-script#71]
Google in the last 10 days has introduced a way to customize Authorization scopes for a GAS project. Your super useful (and critical to us - thank you) npm package does not support the file it uses - appsscript.json
More information at:
 https://developers.google.com/apps-script/concepts/scopes

Our team has a patch so that your upload and init processes accept .json files. We will submit a pull request. Assuming you are ok with it, please consider accepting it.

**Comment by rakeshjoezoo** [comment]
This fix may need to get stricter to allow only "appsscript.json" and not any other json files.

**Comment by lricoy** [comment]
I've been using the fork and it works fine.

**Comment by lricoy** [comment]
Fixed by #73
