### ISSUE TITLE
Note on multiple Google logins

### ISSUE THREAD

**Issue by dsernst** [danthareja/node-google-apps-script#9]
I use multiple Google logins, for personal & work. When I clicked the link in Step 1:

> Create a new project in the Google Developer Console for this tool to access your Google drive. [Using this link guides you through the process and activates the Drive API automatically.](https://console.developers.google.com/start/api?id=drive&credential=client_key)

It began configuring access for one of my accounts, but not the one I needed. This became clear later on when choosing my email address from the dropdown (3 sub-bullets later).

I was able to get around this issue by appending `&authuser=1` (it's 0-indexed) as an extra parameter to the link from the instructions, like so:

https://console.developers.google.com/start/api?id=drive&credential=client_key&authuser=1

Putting this here in case others run into the same issue. :smile:

**Comment by danthareja** [comment]
Excellent detective work @dsernst. Time for some documentation updates

**Comment by danthareja** [comment]
Addressed in v1.0

**Comment by dsernst** [comment]
:+1:
